version: '3.8'

services:
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: kbulatovic
            POSTGRES_PASSWORD: billups1234
            POSTGRES_DB: billups
        ports:
            - '5432:5432'
    migrations:
        build:
            context: .
            dockerfile: packages/migrations/Dockerfile
        depends_on:
            - db
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: kbulatovic
            POSTGRES_PASSWORD: billups1234
            POSTGRES_DB: billups
    api:
        build:
            context: .
            dockerfile: packages/api/Dockerfile
        ports:
            - '8000:8000'
        depends_on:
            - db
            - migrations
        develop:
            watch:
                - action: sync+restart
                  path: packages/api
                  target: /app/packages/api
                  ignore:
                      - node_modules
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: kbulatovic
            POSTGRES_PASSWORD: billups1234
            POSTGRES_DB: billups
    client:
        build:
            context: .
            dockerfile: packages/client/Dockerfile
        ports:
            - '3000:3000'
        develop:
            watch:
                - action: sync+restart
                  path: packages/client
                  target: /app/packages/client
                  ignore:
                      - node_modules
        depends_on:
            - db
            - migrations
volumes:
    pgdata:
